### ISSUE TITLE
Support wildcards in exports

### ISSUE THREAD

**Issue by wagenet** [privatenumber/pkgroll#78] opened 2024-08-01 17:10 UTC
### Feature request

Node supports wildcards in exports, e.g `"./features/*.js": "./src/features/*.js". It would be great if pkgroll could support this case as well.

### Motivations

I want to export everything in one directory and don't want to have to list each one specifically.

### Alternatives

You can write out the list manually, though it's annoying.

### Additional context

https://nodejs.org/api/packages.html#subpath-patterns

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment] 2024-08-01 17:14
Duplicate of https://github.com/privatenumber/pkgroll/issues/38

**Closed by privatenumber** 2024-08-01 17:14 UTC
Labels: enhancement
